DROP DATABASE IF EXISTS SHOP;
CREATE DATABASE SHOP DEFAULT CHARACTER SET UTF8 COLLATE UTF8_BIN;
use shop;

-- 用户账户表
DROP TABLE IF EXISTS USER_ACCOUNT;
-- 人员表
DROP TABLE IF EXISTS PERSON_INFO;
-- 商铺表
DROP TABLE IF EXISTS STORE;
-- 商品类型表
DROP TABLE IF EXISTS GOODS_TYPE;
-- 商铺商品表
DROP TABLE IF EXISTS STORE_GOODS;
-- 订单信息表
DROP TABLE IF EXISTS ORDERINFO;
-- 购买的商品表
DROP TABLE IF EXISTS Buy_GOODS;
-- 支付流水
DROP TABLE IF EXISTS PAY_WATER;


-- 用户账户表
CREATE TABLE USER_ACCOUNT (
   ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键 ',
   USER_ACCOUNT_NAME varchar(30) NOT NULL COMMENT '用户账户名',
   USER_ACCOUNT_PASSWORD varchar(30) NOT NULL COMMENT '密码',
   PAYING_PASSWORD INT(6) NOT NULL COMMENT '支付密码',
	 MONEY NUMERIC(15,3) DEFAULT 0.0 COMMENT '余额',
   REGISTER_TIME DATETIME  COMMENT '注册日期',
	 IS_BUYER TINYINT(1) COMMENT'是否卖家',
   IS_FREEZING TINYINT(1) DEFAULT 0 COMMENT '是否冻结 1--是,0--否',
   IS_LOST TINYINT(1) DEFAULT 0 COMMENT '是否注销 1--是,0--否',
   IS_DELETE TINYINT(1) DEFAULT 0 COMMENT '是否删除 1--是,0--否'
) ENGINE=INNODB COMMENT='支付管理表';


-- 人员信息表
CREATE TABLE PERSON_INFO (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键 ',
	USER_ACCOUNT_ID BIGINT COMMENT'账户的id',
  IDENTITY_CARD VARCHAR(20)  UNIQUE COMMENT '身份证号',
  `NAME` VARCHAR(20) NOT NULL COMMENT '姓名', 
  AGE  INT  COMMENT '年龄' ,
  SEX  TINYINT(2) DEFAULT 0 COMMENT '性别：0 -男，1 -女' , 
	CONSTRAINT FK_PERSON_INFO_USER_ACCOUNT FOREIGN KEY(USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID)
)ENGINE=INNODB COMMENT'人员信息表'; 


-- SHOW VARIABLES LIKE '%timeout%';

-- 商铺表
CREATE TABLE STORE(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	STORE_NAME VARCHAR(50) COMMENT'商铺名称',
	USER_ACCOUNT_ID BIGINT NOT NULL COMMENT '卖家信息',
	CONSTRAINT FK_STORE_USER_ACCOUNT FOREIGN KEY(USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID)
)ENGINE=INNODB COMMENT'商铺表';


-- 商品类型表
CREATE TABLE GOODS_TYPE(
	ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	TYPE_NAME VARCHAR(50) 
)ENGINE=INNODB COMMENT'商品类型表';


-- 商铺商品表
CREATE TABLE STORE_GOODS(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	STORE_ID BIGINT COMMENT'商铺名称',
	GOODS_NAME VARCHAR(50) NOT NULL COMMENT'商品名称',
	GOODS_NUM DOUBLE DEFAULT 0.0 COMMENT'商品库存',
	GOODS_PRICE NUMERIC(15,3)  COMMENT'商品价格',
	GOODS_TYPE_ID INT  COMMENT'商品类型',
	BRAND VARCHAR(50)  COMMENT'品牌',
	PRODUCTION_ADDRESS VARCHAR(50) COMMENT'生产地址',
	PRODUCED_DATE DATE  COMMENT'生产日期 yyyy-MM-dd',
	SHELF_LIFE INT  COMMENT'保质期 ',
	SHELF_LIFE_TYPE TINYINT(2) COMMENT'保质期类型 1-年 2-月 3-日',
	CONSTRAINT FK_STORE_GOODS_STORE FOREIGN KEY(STORE_ID) REFERENCES STORE(ID),
	CONSTRAINT FK_STORE_GOODS_TYPE FOREIGN KEY(GOODS_TYPE_ID) REFERENCES GOODS_TYPE(ID)
)ENGINE=INNODB COMMENT'商铺商品表';


-- 订单信息表
CREATE TABLE ORDER_INFO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键id',
	ORDER_NUM VARCHAR(30) NOT NULL COMMENT '订单编号',
	ORDER_STATUS TINYINT(2) COMMENT'订单状态 1- 待支付 2- 已支付 3-待发货 4-已发货 5-已送达 6-已收货 7-交易成功 8-交易未成功',
	BUYER_USER_ACCOUNT_ID BIGINT NOT NULL COMMENT '买家信息',
	STORE_ID BIGINT NOT NULL COMMENT '商铺信息',
	GOODS_INFO VARCHAR(100) NOT NULL COMMENT '商品信息',
	GOODS_SUM_MONEY NUMERIC(15,3) COMMENT '购买商品总金额',
	ORDER_TIME DATETIME NOT NULL COMMENT '下单时间 yyyy-MM-dd HH:mm:ss',
	DELIVER_TIME DATETIME NOT NULL COMMENT '发货时间 yyyy-MM-dd HH:mm:ss',
	SUCCESS_TIME DATETIME NOT NULL COMMENT '交易成功时间 yyyy-MM-dd HH:mm:ss',
	IS_CANCELLATION TINYINT(1) DEFAULT '0' COMMENT'是否作废 0-否,1-是',
	CONSTRAINT FK_ORDERINFO_BUYER_USER_ACCOUNT FOREIGN KEY(BUYER_USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
	CONSTRAINT FK_ORDERINFO_STORE FOREIGN KEY(STORE_ID) REFERENCES STORE(ID)
)ENGINE = INNODB COMMENT'订单信息表';




-- 购买的商品表
CREATE TABLE BUY_GOODS(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT'主键ID',
	USER_ACCOUNT_ID BIGINT NOT NULL COMMENT'购买商品的账户',
	ORDER_INFO_ID BIGINT NOT NULL COMMENT'购买商品时对应的订单',
	STORE_GOODS_ID BIGINT NOT NULL COMMENT'商铺商品',
	GOODS_NUM DOUBLE DEFAULT 0.0 COMMENT'购买的商品数量',
	BUY_GOODS_DATE DATE COMMENT'购买商品的时间',
	CONSTRAINT FK_BUY_GOODS_USER_ACCOUNT FOREIGN KEY(USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
	CONSTRAINT FK_BUY_GOODS_ORDER_INFO FOREIGN KEY(ORDER_INFO_ID) REFERENCES ORDER_INFO(ID),
	CONSTRAINT FK_BUY_GOODS_STORE_GOODS FOREIGN KEY(STORE_GOODS_ID) REFERENCES STORE_GOODS(ID)
)ENGINE=INNODB COMMENT'购买的商品表';



-- 支付流水
CREATE TABLE PAY_WATER(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
	BUYER_USER_ACCOUNT_ID BIGINT NOT NULL COMMENT '买家信息',
	SELLER_USER_ACCOUNT_ID BIGINT NOT NULL COMMENT '卖家信息',
	PAY_WATER_NUMBER VARCHAR(50) NOT NULL UNIQUE COMMENT '流水编号',
	RECORD_TYPE TINYINT(2) DEFAULT 1  COMMENT '记录类型,1-收入，0-支出',
	TRANSACTION_AMOUNT NUMERIC(15,3) DEFAULT 0.00 COMMENT '交易金额',
	CREATE_TRANSACTION DATETIME COMMENT '创建交易时间 yyyy-MM-dd HH:mm:ss',
	TRANSACTION_TIME DATETIME COMMENT '交易完成时间 yyyy-MM-dd HH:mm:ss',
	CONSTRAINT FK_PAY_WATER_BUYER_USER_ACCOUNT FOREIGN KEY(BUYER_USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID),
	CONSTRAINT FK_PAY_WATER_SELLER_USER_ACCOUNT FOREIGN KEY(SELLER_USER_ACCOUNT_ID) REFERENCES USER_ACCOUNT(ID)
)ENGINE=INNODB COMMENT'支付流水表';













